import type { ExpenseRecord } from './ExpenseList'

export const mockExpenses: Array<ExpenseRecord> = [
  {
    id: '1',
    date: 'Today, Feb 4',
    totalAmount: 142.5,
    transactions: [
      {
        id: 't1',
        description: 'Grocery Store',
        name: 'Food',
        category_id: 'cat-food',
        icon: '🛒',
        color: '#22c55e',
        amount: 87.5,
        transaction_date: '2026-02-04',
        is_recurring: false,
      },
      {
        id: 't2',
        description: 'Netflix',
        name: 'Entertainment',
        category_id: 'cat-entertainment',
        icon: '🎬',
        color: '#ef4444',
        amount: 15.0,
        transaction_date: '2026-02-04',
        is_recurring: true,
      },
      {
        id: 't3',
        description: 'Uber Ride',
        name: 'Transport',
        category_id: 'cat-transport',
        icon: '🚗',
        color: '#3b82f6',
        amount: 40.0,
        transaction_date: '2026-02-04',
        is_recurring: false,
      },
    ],
  },
  {
    id: '2',
    date: 'Yesterday, Feb 3',
    totalAmount: 234.0,
    transactions: [
      {
        id: 't4',
        description: 'Electric Bill',
        name: 'Utilities',
        category_id: 'cat-utilities',
        icon: '⚡',
        color: '#f59e0b',
        amount: 120.0,
        transaction_date: '2026-02-03',
        is_recurring: true,
      },
      {
        id: 't5',
        description: 'Coffee Shop',
        name: 'Food',
        category_id: 'cat-food',
        icon: '☕',
        color: '#22c55e',
        amount: 14.0,
        transaction_date: '2026-02-03',
        is_recurring: false,
      },
      {
        id: 't6',
        description: 'Gym Membership',
        name: 'Health',
        category_id: 'cat-health',
        icon: '💪',
        color: '#8b5cf6',
        amount: 50.0,
        transaction_date: '2026-02-03',
        is_recurring: true,
      },
      {
        id: 't7',
        description: 'Amazon',
        name: 'Shopping',
        category_id: 'cat-shopping',
        icon: '📦',
        color: '#ec4899',
        amount: 50.0,
        transaction_date: '2026-02-03',
        is_recurring: false,
      },
    ],
  },
  {
    id: '3',
    date: 'Feb 2',
    totalAmount: 63.0,
    transactions: [
      {
        id: 't8',
        description: 'Spotify',
        name: 'Entertainment',
        category_id: 'cat-entertainment',
        icon: '🎵',
        color: '#ef4444',
        amount: 9.99,
        transaction_date: '2026-02-02',
        is_recurring: true,
      },
      {
        id: 't9',
        description: 'Restaurant',
        name: 'Food',
        category_id: 'cat-food',
        icon: '🍽️',
        color: '#22c55e',
        amount: 53.01,
        transaction_date: '2026-02-02',
        is_recurring: false,
      },
    ],
  },
]
