import type { ExpenseRecord } from './ExpenseList'

export const mockExpenses: Array<ExpenseRecord> = [
  {
    id: '1',
    date: 'Today, Feb 4',
    totalAmount: 142.5,
    transactions: [
      {
        id: 't1',
        title: 'Grocery Store',
        category: 'Food',
        icon: '🛒',
        color: '#22c55e',
        amount: 87.5,
        date: '2026-02-04',
      },
      {
        id: 't2',
        title: 'Netflix',
        category: 'Entertainment',
        icon: '🎬',
        color: '#ef4444',
        amount: 15.0,
        date: '2026-02-04',
      },
      {
        id: 't3',
        title: 'Uber Ride',
        category: 'Transport',
        icon: '🚗',
        color: '#3b82f6',
        amount: 40.0,
        date: '2026-02-04',
      },
    ],
  },
  {
    id: '2',
    date: 'Yesterday, Feb 3',
    totalAmount: 234.0,
    transactions: [
      {
        id: 't4',
        title: 'Electric Bill',
        category: 'Utilities',
        icon: '⚡',
        color: '#f59e0b',
        amount: 120.0,
        date: '2026-02-03',
      },
      {
        id: 't5',
        title: 'Coffee Shop',
        category: 'Food',
        icon: '☕',
        color: '#22c55e',
        amount: 14.0,
        date: '2026-02-03',
      },
      {
        id: 't6',
        title: 'Gym Membership',
        category: 'Health',
        icon: '💪',
        color: '#8b5cf6',
        amount: 50.0,
        date: '2026-02-03',
      },
      {
        id: 't7',
        title: 'Amazon',
        category: 'Shopping',
        icon: '📦',
        color: '#ec4899',
        amount: 50.0,
        date: '2026-02-03',
      },
    ],
  },
  {
    id: '3',
    date: 'Feb 2',
    totalAmount: 63.0,
    transactions: [
      {
        id: 't8',
        title: 'Spotify',
        category: 'Entertainment',
        icon: '🎵',
        color: '#ef4444',
        amount: 9.99,
        date: '2026-02-02',
      },
      {
        id: 't9',
        title: 'Restaurant',
        category: 'Food',
        icon: '🍽️',
        color: '#22c55e',
        amount: 53.01,
        date: '2026-02-02',
      },
    ],
  },
]
