/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AppTransactionsIndexRouteImport } from './routes/_app/transactions/index'
import { Route as AppRecurringExpensesIndexRouteImport } from './routes/_app/recurring-expenses/index'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppIaInsightsIndexRouteImport } from './routes/_app/ia-insights/index'
import { Route as AppGoalTrackerIndexRouteImport } from './routes/_app/goal-tracker/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppBudgetIndexRouteImport } from './routes/_app/budget/index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecurringExpensesIndexRoute =
  AppRecurringExpensesIndexRouteImport.update({
    id: '/recurring-expenses/',
    path: '/recurring-expenses/',
    getParentRoute: () => AppRoute,
  } as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppIaInsightsIndexRoute = AppIaInsightsIndexRouteImport.update({
  id: '/ia-insights/',
  path: '/ia-insights/',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalTrackerIndexRoute = AppGoalTrackerIndexRouteImport.update({
  id: '/goal-tracker/',
  path: '/goal-tracker/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetIndexRoute = AppBudgetIndexRouteImport.update({
  id: '/budget/',
  path: '/budget/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof PublicIndexRoute
  '/budget': typeof AppBudgetIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/goal-tracker': typeof AppGoalTrackerIndexRoute
  '/ia-insights': typeof AppIaInsightsIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/recurring-expenses': typeof AppRecurringExpensesIndexRoute
  '/transactions': typeof AppTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof PublicIndexRoute
  '/budget': typeof AppBudgetIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/goal-tracker': typeof AppGoalTrackerIndexRoute
  '/ia-insights': typeof AppIaInsightsIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/recurring-expenses': typeof AppRecurringExpensesIndexRoute
  '/transactions': typeof AppTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/budget/': typeof AppBudgetIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/goal-tracker/': typeof AppGoalTrackerIndexRoute
  '/_app/ia-insights/': typeof AppIaInsightsIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/recurring-expenses/': typeof AppRecurringExpensesIndexRoute
  '/_app/transactions/': typeof AppTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/budget'
    | '/dashboard'
    | '/goal-tracker'
    | '/ia-insights'
    | '/profile'
    | '/recurring-expenses'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/budget'
    | '/dashboard'
    | '/goal-tracker'
    | '/ia-insights'
    | '/profile'
    | '/recurring-expenses'
    | '/transactions'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_public/'
    | '/_app/budget/'
    | '/_app/dashboard/'
    | '/_app/goal-tracker/'
    | '/_app/ia-insights/'
    | '/_app/profile/'
    | '/_app/recurring-expenses/'
    | '/_app/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transactions/': {
      id: '/_app/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recurring-expenses/': {
      id: '/_app/recurring-expenses/'
      path: '/recurring-expenses'
      fullPath: '/recurring-expenses'
      preLoaderRoute: typeof AppRecurringExpensesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia-insights/': {
      id: '/_app/ia-insights/'
      path: '/ia-insights'
      fullPath: '/ia-insights'
      preLoaderRoute: typeof AppIaInsightsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goal-tracker/': {
      id: '/_app/goal-tracker/'
      path: '/goal-tracker'
      fullPath: '/goal-tracker'
      preLoaderRoute: typeof AppGoalTrackerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget/': {
      id: '/_app/budget/'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AppBudgetIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBudgetIndexRoute: typeof AppBudgetIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppGoalTrackerIndexRoute: typeof AppGoalTrackerIndexRoute
  AppIaInsightsIndexRoute: typeof AppIaInsightsIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppRecurringExpensesIndexRoute: typeof AppRecurringExpensesIndexRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetIndexRoute: AppBudgetIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppGoalTrackerIndexRoute: AppGoalTrackerIndexRoute,
  AppIaInsightsIndexRoute: AppIaInsightsIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppRecurringExpensesIndexRoute: AppRecurringExpensesIndexRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
