/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppIaInsightsIndexRouteImport } from './routes/_app/ia-insights/index'
import { Route as AppGoalTrackerIndexRouteImport } from './routes/_app/goal-tracker/index'
import { Route as AppDebtCalculatorIndexRouteImport } from './routes/_app/debt-calculator/index'
import { Route as AppBudgetIndexRouteImport } from './routes/_app/budget/index'
import { Route as AppBudgetOverviewRouteImport } from './routes/_app/budget/overview'
import { Route as AppBudgetBudgetIdRouteImport } from './routes/_app/budget/$budgetId'
import { Route as AppBudgetBudgetIdExpensesRouteImport } from './routes/_app/budget/$budgetId/expenses'
import { Route as AppBudgetBudgetIdDashboardRouteImport } from './routes/_app/budget/$budgetId/dashboard'
import { Route as AppBudgetBudgetIdCategoriesRouteImport } from './routes/_app/budget/$budgetId/categories'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppIaInsightsIndexRoute = AppIaInsightsIndexRouteImport.update({
  id: '/ia-insights/',
  path: '/ia-insights/',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalTrackerIndexRoute = AppGoalTrackerIndexRouteImport.update({
  id: '/goal-tracker/',
  path: '/goal-tracker/',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtCalculatorIndexRoute = AppDebtCalculatorIndexRouteImport.update({
  id: '/debt-calculator/',
  path: '/debt-calculator/',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetIndexRoute = AppBudgetIndexRouteImport.update({
  id: '/budget/',
  path: '/budget/',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetOverviewRoute = AppBudgetOverviewRouteImport.update({
  id: '/budget/overview',
  path: '/budget/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetBudgetIdRoute = AppBudgetBudgetIdRouteImport.update({
  id: '/budget/$budgetId',
  path: '/budget/$budgetId',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetBudgetIdExpensesRoute =
  AppBudgetBudgetIdExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AppBudgetBudgetIdRoute,
  } as any)
const AppBudgetBudgetIdDashboardRoute =
  AppBudgetBudgetIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AppBudgetBudgetIdRoute,
  } as any)
const AppBudgetBudgetIdCategoriesRoute =
  AppBudgetBudgetIdCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AppBudgetBudgetIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/budget/$budgetId': typeof AppBudgetBudgetIdRouteWithChildren
  '/budget/overview': typeof AppBudgetOverviewRoute
  '/budget/': typeof AppBudgetIndexRoute
  '/debt-calculator/': typeof AppDebtCalculatorIndexRoute
  '/goal-tracker/': typeof AppGoalTrackerIndexRoute
  '/ia-insights/': typeof AppIaInsightsIndexRoute
  '/profile/': typeof AppProfileIndexRoute
  '/budget/$budgetId/categories': typeof AppBudgetBudgetIdCategoriesRoute
  '/budget/$budgetId/dashboard': typeof AppBudgetBudgetIdDashboardRoute
  '/budget/$budgetId/expenses': typeof AppBudgetBudgetIdExpensesRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/budget/$budgetId': typeof AppBudgetBudgetIdRouteWithChildren
  '/budget/overview': typeof AppBudgetOverviewRoute
  '/budget': typeof AppBudgetIndexRoute
  '/debt-calculator': typeof AppDebtCalculatorIndexRoute
  '/goal-tracker': typeof AppGoalTrackerIndexRoute
  '/ia-insights': typeof AppIaInsightsIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/budget/$budgetId/categories': typeof AppBudgetBudgetIdCategoriesRoute
  '/budget/$budgetId/dashboard': typeof AppBudgetBudgetIdDashboardRoute
  '/budget/$budgetId/expenses': typeof AppBudgetBudgetIdExpensesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/budget/$budgetId': typeof AppBudgetBudgetIdRouteWithChildren
  '/_app/budget/overview': typeof AppBudgetOverviewRoute
  '/_app/budget/': typeof AppBudgetIndexRoute
  '/_app/debt-calculator/': typeof AppDebtCalculatorIndexRoute
  '/_app/goal-tracker/': typeof AppGoalTrackerIndexRoute
  '/_app/ia-insights/': typeof AppIaInsightsIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/budget/$budgetId/categories': typeof AppBudgetBudgetIdCategoriesRoute
  '/_app/budget/$budgetId/dashboard': typeof AppBudgetBudgetIdDashboardRoute
  '/_app/budget/$budgetId/expenses': typeof AppBudgetBudgetIdExpensesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/budget/$budgetId'
    | '/budget/overview'
    | '/budget/'
    | '/debt-calculator/'
    | '/goal-tracker/'
    | '/ia-insights/'
    | '/profile/'
    | '/budget/$budgetId/categories'
    | '/budget/$budgetId/dashboard'
    | '/budget/$budgetId/expenses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/budget/$budgetId'
    | '/budget/overview'
    | '/budget'
    | '/debt-calculator'
    | '/goal-tracker'
    | '/ia-insights'
    | '/profile'
    | '/budget/$budgetId/categories'
    | '/budget/$budgetId/dashboard'
    | '/budget/$budgetId/expenses'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_public/'
    | '/_app/budget/$budgetId'
    | '/_app/budget/overview'
    | '/_app/budget/'
    | '/_app/debt-calculator/'
    | '/_app/goal-tracker/'
    | '/_app/ia-insights/'
    | '/_app/profile/'
    | '/_app/budget/$budgetId/categories'
    | '/_app/budget/$budgetId/dashboard'
    | '/_app/budget/$budgetId/expenses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia-insights/': {
      id: '/_app/ia-insights/'
      path: '/ia-insights'
      fullPath: '/ia-insights/'
      preLoaderRoute: typeof AppIaInsightsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goal-tracker/': {
      id: '/_app/goal-tracker/'
      path: '/goal-tracker'
      fullPath: '/goal-tracker/'
      preLoaderRoute: typeof AppGoalTrackerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debt-calculator/': {
      id: '/_app/debt-calculator/'
      path: '/debt-calculator'
      fullPath: '/debt-calculator/'
      preLoaderRoute: typeof AppDebtCalculatorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget/': {
      id: '/_app/budget/'
      path: '/budget'
      fullPath: '/budget/'
      preLoaderRoute: typeof AppBudgetIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget/overview': {
      id: '/_app/budget/overview'
      path: '/budget/overview'
      fullPath: '/budget/overview'
      preLoaderRoute: typeof AppBudgetOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget/$budgetId': {
      id: '/_app/budget/$budgetId'
      path: '/budget/$budgetId'
      fullPath: '/budget/$budgetId'
      preLoaderRoute: typeof AppBudgetBudgetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget/$budgetId/expenses': {
      id: '/_app/budget/$budgetId/expenses'
      path: '/expenses'
      fullPath: '/budget/$budgetId/expenses'
      preLoaderRoute: typeof AppBudgetBudgetIdExpensesRouteImport
      parentRoute: typeof AppBudgetBudgetIdRoute
    }
    '/_app/budget/$budgetId/dashboard': {
      id: '/_app/budget/$budgetId/dashboard'
      path: '/dashboard'
      fullPath: '/budget/$budgetId/dashboard'
      preLoaderRoute: typeof AppBudgetBudgetIdDashboardRouteImport
      parentRoute: typeof AppBudgetBudgetIdRoute
    }
    '/_app/budget/$budgetId/categories': {
      id: '/_app/budget/$budgetId/categories'
      path: '/categories'
      fullPath: '/budget/$budgetId/categories'
      preLoaderRoute: typeof AppBudgetBudgetIdCategoriesRouteImport
      parentRoute: typeof AppBudgetBudgetIdRoute
    }
  }
}

interface AppBudgetBudgetIdRouteChildren {
  AppBudgetBudgetIdCategoriesRoute: typeof AppBudgetBudgetIdCategoriesRoute
  AppBudgetBudgetIdDashboardRoute: typeof AppBudgetBudgetIdDashboardRoute
  AppBudgetBudgetIdExpensesRoute: typeof AppBudgetBudgetIdExpensesRoute
}

const AppBudgetBudgetIdRouteChildren: AppBudgetBudgetIdRouteChildren = {
  AppBudgetBudgetIdCategoriesRoute: AppBudgetBudgetIdCategoriesRoute,
  AppBudgetBudgetIdDashboardRoute: AppBudgetBudgetIdDashboardRoute,
  AppBudgetBudgetIdExpensesRoute: AppBudgetBudgetIdExpensesRoute,
}

const AppBudgetBudgetIdRouteWithChildren =
  AppBudgetBudgetIdRoute._addFileChildren(AppBudgetBudgetIdRouteChildren)

interface AppRouteChildren {
  AppBudgetBudgetIdRoute: typeof AppBudgetBudgetIdRouteWithChildren
  AppBudgetOverviewRoute: typeof AppBudgetOverviewRoute
  AppBudgetIndexRoute: typeof AppBudgetIndexRoute
  AppDebtCalculatorIndexRoute: typeof AppDebtCalculatorIndexRoute
  AppGoalTrackerIndexRoute: typeof AppGoalTrackerIndexRoute
  AppIaInsightsIndexRoute: typeof AppIaInsightsIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetBudgetIdRoute: AppBudgetBudgetIdRouteWithChildren,
  AppBudgetOverviewRoute: AppBudgetOverviewRoute,
  AppBudgetIndexRoute: AppBudgetIndexRoute,
  AppDebtCalculatorIndexRoute: AppDebtCalculatorIndexRoute,
  AppGoalTrackerIndexRoute: AppGoalTrackerIndexRoute,
  AppIaInsightsIndexRoute: AppIaInsightsIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
